server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql1205
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  thread:
    virtual:
      enabled: true   # Java 21 虚拟线程

logging:
  level:
    com.example.demo: debug

jwt:
  secret: demo-very-long-secret-key
  expiration: 86400000 # 1d